/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import bussines_logical.Carro;
import bussines_logical.Moto;
import bussines_logical.Sensor;
import static bussines_logical.Vehiculo.vehiculos;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;

public class GUIIngresoVehiculo extends javax.swing.JFrame {

    /**
     * Creates new form GUIIngresoVehiculo
     */
    public GUIIngresoVehiculo() {
        initComponents();
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLpisoIngresovehiculo = new javax.swing.JLabel();
        jLespacioIngresovehiculo = new javax.swing.JLabel();
        jLmarcaIngresovehiculo = new javax.swing.JLabel();
        jLplacaIngresovehiculo = new javax.swing.JLabel();
        jLtipoIngresovehiculo = new javax.swing.JLabel();
        jTFpisoIngresovehiculo = new javax.swing.JTextField();
        jTFespacioIngresovehiculo = new javax.swing.JTextField();
        jTFplacaIngresovehiculo = new javax.swing.JTextField();
        jTFmarcaIngresovehiculo = new javax.swing.JTextField();
        jLcolorIngresovehiculo = new javax.swing.JLabel();
        jTFcolorIngresovehiculo = new javax.swing.JTextField();
        jSmedioIngresovehiculo = new javax.swing.JSeparator();
        jLubicacionIngresovehiculo = new javax.swing.JLabel();
        jSubicacionIngresovehiculo = new javax.swing.JSeparator();
        jSeinformacionIngresovehiculo = new javax.swing.JSeparator();
        jLinformacionIngresovehiculo = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(227, 227, 124));

        jLpisoIngresovehiculo.setText("Piso");

        jLespacioIngresovehiculo.setText("Espacio");

        jLmarcaIngresovehiculo.setText("Marca");

        jLplacaIngresovehiculo.setText("Placa");

        jLtipoIngresovehiculo.setText("Tipo");

        jTFespacioIngresovehiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFespacioIngresovehiculoActionPerformed(evt);
            }
        });

        jTFplacaIngresovehiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFplacaIngresovehiculoActionPerformed(evt);
            }
        });

        jLcolorIngresovehiculo.setText("Color");

        jTFcolorIngresovehiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFcolorIngresovehiculoActionPerformed(evt);
            }
        });

        jSmedioIngresovehiculo.setForeground(new java.awt.Color(0, 0, 0));
        jSmedioIngresovehiculo.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jLubicacionIngresovehiculo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLubicacionIngresovehiculo.setText("Ubicación");

        jSubicacionIngresovehiculo.setForeground(new java.awt.Color(0, 0, 0));

        jSeinformacionIngresovehiculo.setForeground(new java.awt.Color(0, 0, 0));

        jLinformacionIngresovehiculo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLinformacionIngresovehiculo.setText("Información");

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Ingresar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(0, 0, 0));
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Cancelar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jComboBox1.setBackground(new java.awt.Color(0, 0, 0));
        jComboBox1.setForeground(new java.awt.Color(255, 255, 255));
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Carro", "Moto" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(37, 37, 37)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jTFespacioIngresovehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTFpisoIngresovehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(58, 58, 58)
                                .addComponent(jLespacioIngresovehiculo))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(64, 64, 64)
                                .addComponent(jLpisoIngresovehiculo))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jSubicacionIngresovehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(30, 30, 30)
                        .addComponent(jSmedioIngresovehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(jLubicacionIngresovehiculo)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLmarcaIngresovehiculo)
                                        .addComponent(jLplacaIngresovehiculo, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLtipoIngresovehiculo, javax.swing.GroupLayout.Alignment.LEADING))
                                    .addComponent(jLcolorIngresovehiculo))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTFmarcaIngresovehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTFplacaIngresovehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTFcolorIngresovehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jSeinformacionIngresovehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 9, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButton1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton2)))
                        .addGap(37, 37, 37))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLinformacionIngresovehiculo)
                        .addGap(101, 101, 101))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLubicacionIngresovehiculo)
                    .addComponent(jLinformacionIngresovehiculo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jSmedioIngresovehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jSeinformacionIngresovehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLtipoIngresovehiculo)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLplacaIngresovehiculo)
                            .addComponent(jTFplacaIngresovehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTFmarcaIngresovehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLmarcaIngresovehiculo))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTFcolorIngresovehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLcolorIngresovehiculo))
                        .addGap(85, 85, 85)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1)
                            .addComponent(jButton2))
                        .addGap(28, 28, 28))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jSubicacionIngresovehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(42, 42, 42)
                        .addComponent(jLpisoIngresovehiculo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTFpisoIngresovehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLespacioIngresovehiculo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTFespacioIngresovehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(90, 90, 90))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(442, 413));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTFespacioIngresovehiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFespacioIngresovehiculoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFespacioIngresovehiculoActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        int piso;
        int espacio;
        String tipo;
        String placa;
        String marca;
        String color;
        

        piso = Integer.parseInt(jTFpisoIngresovehiculo.getText());
        espacio = Integer.parseInt(jTFespacioIngresovehiculo.getText());
        tipo =  jComboBox1.getSelectedItem().toString();
        placa = jTFplacaIngresovehiculo.getText();
        marca = jTFmarcaIngresovehiculo.getText();
        color = jTFcolorIngresovehiculo.getText();

        if (Sensor.sensores[piso][espacio] != null) {

            JOptionPane.showMessageDialog(this, "Espacio LLeno", "Dialog",
                    JOptionPane.ERROR_MESSAGE);
        } else {

            Date fecha = new Date();
            DateFormat fechaFormat = new SimpleDateFormat("dd/MM/yyyy");
            DateFormat horaFormat = new SimpleDateFormat("HH:mm:ss");
    
            

            
            JOptionPane.showMessageDialog(this, "Se ingreso correctamente el Vehiculo", "Dialog",
                    JOptionPane.INFORMATION_MESSAGE);

            if (tipo.equalsIgnoreCase("Moto")) {
                Moto.vehiculos[piso][espacio] = new Moto(placa, marca, color, tipo, fechaFormat, horaFormat);
            } else if (tipo.equalsIgnoreCase("Carro")) {
                Carro.vehiculos[piso][espacio] = new Carro(placa, marca, color, tipo, fechaFormat, horaFormat);
            } else {
                System.out.println("El tipo de Vehiculo ingresado es incorrecto");
            }

            Sensor.sensores[piso][espacio] = new Sensor(1);
        }
            
            this.dispose();

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       
        this.dispose();
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTFcolorIngresovehiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFcolorIngresovehiculoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFcolorIngresovehiculoActionPerformed

    private void jTFplacaIngresovehiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFplacaIngresovehiculoActionPerformed
       
    }//GEN-LAST:event_jTFplacaIngresovehiculoActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUIIngresoVehiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUIIngresoVehiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUIIngresoVehiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUIIngresoVehiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUIIngresoVehiculo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    public static javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLcolorIngresovehiculo;
    private javax.swing.JLabel jLespacioIngresovehiculo;
    private javax.swing.JLabel jLinformacionIngresovehiculo;
    private javax.swing.JLabel jLmarcaIngresovehiculo;
    private javax.swing.JLabel jLpisoIngresovehiculo;
    private javax.swing.JLabel jLplacaIngresovehiculo;
    private javax.swing.JLabel jLtipoIngresovehiculo;
    private javax.swing.JLabel jLubicacionIngresovehiculo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeinformacionIngresovehiculo;
    private javax.swing.JSeparator jSmedioIngresovehiculo;
    private javax.swing.JSeparator jSubicacionIngresovehiculo;
    public static javax.swing.JTextField jTFcolorIngresovehiculo;
    private javax.swing.JTextField jTFespacioIngresovehiculo;
    public static javax.swing.JTextField jTFmarcaIngresovehiculo;
    private javax.swing.JTextField jTFpisoIngresovehiculo;
    public static javax.swing.JTextField jTFplacaIngresovehiculo;
    // End of variables declaration//GEN-END:variables
}
