/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import bussines_logical.Sensor;
import bussines_logical.Vehiculo;
import java.awt.Color;
import java.io.File;
import java.io.FileOutputStream;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintStream;
import java.util.HashSet;
import java.util.Set;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;


public class GUIPrincipal extends javax.swing.JFrame {

    private int pisos;
    private int espacio;
    public static int precioMoto;
    public static int precioCarro;

    public Vehiculo[][] vehiculos_dia;
    public Sensor[][] sensor_dia;

    /**
     * Creates new form Principal
     */
    public GUIPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jTabbedPanelPrincipal = new javax.swing.JTabbedPane();
        jPconfiguracioninicialPrincipal = new javax.swing.JPanel();
        jLpisosPrincipal = new javax.swing.JLabel();
        jLespaciosPrincipal = new javax.swing.JLabel();
        jTFpisosPrincipal = new javax.swing.JTextField();
        jTFespaciosPrincipal = new javax.swing.JTextField();
        jLvalorcarroPrincipal = new javax.swing.JLabel();
        jLvalormotoPrincipal = new javax.swing.JLabel();
        jTFvalorcarroPrincipal = new javax.swing.JTextField();
        jTFvalormotoPrincipal = new javax.swing.JTextField();
        jBsalirPrincipal = new javax.swing.JButton();
        jBfijarPrincipal = new javax.swing.JButton();
        jBreiniciarPrincipal = new javax.swing.JButton();
        jSpropiedadesPrincipal = new javax.swing.JSeparator();
        jLpropiedadesPrincipal = new javax.swing.JLabel();
        jSvaloresmonetariosPrincipal = new javax.swing.JSeparator();
        jLvaloresmonetariosPrincipal = new javax.swing.JLabel();
        jPinformesPrincipal = new javax.swing.JPanel();
        jBimprimirpuestosPrincipal = new javax.swing.JButton();
        jBimprimirdatosPrincipal = new javax.swing.JButton();
        jBcantidadvehiculosPrincipal = new javax.swing.JButton();
        jBbuscarplacaPrincipal = new javax.swing.JButton();
        jTplacaPrincipal = new javax.swing.JTextField();
        jSbuscarporplacaPrincipal = new javax.swing.JSeparator();
        jLbuscarporplacaPrincipal = new javax.swing.JLabel();
        jSgestiondeinformacionPrincipal = new javax.swing.JSeparator();
        jLgestiondeinformacionPrincipal = new javax.swing.JLabel();
        jPoperacionesbasicasPrincipal = new javax.swing.JPanel();
        jBingresarvehiculoPrincipal = new javax.swing.JButton();
        jBretirarvehiculoPrincipal = new javax.swing.JButton();
        jBverificarespacioPrincipal = new javax.swing.JButton();
        jTFespacioPrincipal = new javax.swing.JTextField();
        jTFpisoPrincipal = new javax.swing.JTextField();
        jLpisoPrincipal = new javax.swing.JLabel();
        jLespacioPrincipal = new javax.swing.JLabel();
        jSverificaciondisponibilidadPrincipal = new javax.swing.JSeparator();
        jLverificaciondisponibilidadPrincipal = new javax.swing.JLabel();
        jSingresoyretirosvehiculosPrincipal = new javax.swing.JSeparator();
        jLingresoyretirosvehiculosPrincipal = new javax.swing.JLabel();
        jPterminardiaPrincipal = new javax.swing.JPanel();
        jBcerrarsesionPrincipal = new javax.swing.JButton();
        jSterminardiaPrincipal = new javax.swing.JSeparator();
        jLterminardiaPrincipal = new javax.swing.JLabel();

        jButton1.setText("Ingresar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("ingresar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("jButton3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Administracion");

        jPconfiguracioninicialPrincipal.setBackground(new java.awt.Color(227, 227, 124));

        jLpisosPrincipal.setText("Pisos");

        jLespaciosPrincipal.setText("Espacios");

        jTFespaciosPrincipal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFespaciosPrincipalActionPerformed(evt);
            }
        });

        jLvalorcarroPrincipal.setText("Valor por carro");

        jLvalormotoPrincipal.setText("Valor moto");

        jTFvalorcarroPrincipal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFvalorcarroPrincipalActionPerformed(evt);
            }
        });

        jTFvalormotoPrincipal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFvalormotoPrincipalActionPerformed(evt);
            }
        });

        jBsalirPrincipal.setBackground(new java.awt.Color(227, 227, 124));
        jBsalirPrincipal.setForeground(new java.awt.Color(227, 227, 124));
        jBsalirPrincipal.setIcon(new javax.swing.ImageIcon("C:\\Users\\Usuario\\Desktop\\sd\\Parqueadero\\src\\main\\java\\GUI\\recursos\\image\\cerrar-sesion.png")); // NOI18N
        jBsalirPrincipal.setBorderPainted(false);
        jBsalirPrincipal.setContentAreaFilled(false);
        jBsalirPrincipal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBsalirPrincipalActionPerformed(evt);
            }
        });

        jBfijarPrincipal.setBackground(new java.awt.Color(227, 227, 124));
        jBfijarPrincipal.setIcon(new javax.swing.ImageIcon("C:\\Users\\Usuario\\Desktop\\sd\\Parqueadero\\src\\main\\java\\GUI\\recursos\\image\\disquete (1).png")); // NOI18N
        jBfijarPrincipal.setBorder(null);
        jBfijarPrincipal.setContentAreaFilled(false);
        jBfijarPrincipal.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jBfijarPrincipal.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jBfijarPrincipalMouseMoved(evt);
            }
        });
        jBfijarPrincipal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBfijarPrincipalActionPerformed(evt);
            }
        });

        jBreiniciarPrincipal.setBackground(new java.awt.Color(227, 227, 124));
        jBreiniciarPrincipal.setForeground(new java.awt.Color(227, 227, 124));
        jBreiniciarPrincipal.setIcon(new javax.swing.ImageIcon("C:\\Users\\Usuario\\Desktop\\sd\\Parqueadero\\src\\main\\java\\GUI\\recursos\\image\\refrescar.png")); // NOI18N
        jBreiniciarPrincipal.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jBreiniciarPrincipal.setBorderPainted(false);
        jBreiniciarPrincipal.setContentAreaFilled(false);
        jBreiniciarPrincipal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBreiniciarPrincipalActionPerformed(evt);
            }
        });

        jSpropiedadesPrincipal.setForeground(new java.awt.Color(0, 0, 0));

        jLpropiedadesPrincipal.setText("Propiedades");

        jSvaloresmonetariosPrincipal.setForeground(new java.awt.Color(0, 0, 0));

        jLvaloresmonetariosPrincipal.setText("Valores monetarios");

        javax.swing.GroupLayout jPconfiguracioninicialPrincipalLayout = new javax.swing.GroupLayout(jPconfiguracioninicialPrincipal);
        jPconfiguracioninicialPrincipal.setLayout(jPconfiguracioninicialPrincipalLayout);
        jPconfiguracioninicialPrincipalLayout.setHorizontalGroup(
            jPconfiguracioninicialPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPconfiguracioninicialPrincipalLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPconfiguracioninicialPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLpropiedadesPrincipal)
                    .addGroup(jPconfiguracioninicialPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jSpropiedadesPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPconfiguracioninicialPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPconfiguracioninicialPrincipalLayout.createSequentialGroup()
                                .addGap(99, 99, 99)
                                .addGroup(jPconfiguracioninicialPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTFvalorcarroPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTFvalormotoPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLvalorcarroPrincipal)
                            .addComponent(jLvaloresmonetariosPrincipal)
                            .addComponent(jSvaloresmonetariosPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPconfiguracioninicialPrincipalLayout.createSequentialGroup()
                                .addGroup(jPconfiguracioninicialPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLpisosPrincipal)
                                    .addComponent(jLespaciosPrincipal))
                                .addGap(45, 45, 45)
                                .addGroup(jPconfiguracioninicialPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTFespaciosPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTFpisosPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLvalormotoPrincipal))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 109, Short.MAX_VALUE)
                .addGroup(jPconfiguracioninicialPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jBsalirPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBreiniciarPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBfijarPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(61, 61, 61))
        );
        jPconfiguracioninicialPrincipalLayout.setVerticalGroup(
            jPconfiguracioninicialPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPconfiguracioninicialPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPconfiguracioninicialPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPconfiguracioninicialPrincipalLayout.createSequentialGroup()
                        .addComponent(jLpropiedadesPrincipal)
                        .addGap(4, 4, 4)
                        .addComponent(jSpropiedadesPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 9, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPconfiguracioninicialPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLpisosPrincipal)
                            .addComponent(jTFpisosPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(jPconfiguracioninicialPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLespaciosPrincipal)
                            .addComponent(jTFespaciosPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(50, 50, 50)
                        .addComponent(jLvaloresmonetariosPrincipal)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSvaloresmonetariosPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPconfiguracioninicialPrincipalLayout.createSequentialGroup()
                        .addComponent(jBfijarPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)))
                .addGroup(jPconfiguracioninicialPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPconfiguracioninicialPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLvalorcarroPrincipal)
                        .addComponent(jTFvalorcarroPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jBreiniciarPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPconfiguracioninicialPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLvalormotoPrincipal)
                    .addComponent(jTFvalormotoPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBsalirPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(59, Short.MAX_VALUE))
        );

        jTabbedPanelPrincipal.addTab("Configuracion Inicial", jPconfiguracioninicialPrincipal);

        jPinformesPrincipal.setBackground(new java.awt.Color(227, 227, 124));

        jBimprimirpuestosPrincipal.setBackground(new java.awt.Color(0, 0, 0));
        jBimprimirpuestosPrincipal.setForeground(new java.awt.Color(255, 255, 255));
        jBimprimirpuestosPrincipal.setText("Imprimir Puestos");
        jBimprimirpuestosPrincipal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBimprimirpuestosPrincipalActionPerformed(evt);
            }
        });

        jBimprimirdatosPrincipal.setBackground(new java.awt.Color(0, 0, 0));
        jBimprimirdatosPrincipal.setForeground(new java.awt.Color(255, 255, 255));
        jBimprimirdatosPrincipal.setText("Imprimir datos de Puestos");
        jBimprimirdatosPrincipal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBimprimirdatosPrincipalActionPerformed(evt);
            }
        });

        jBcantidadvehiculosPrincipal.setBackground(new java.awt.Color(0, 0, 0));
        jBcantidadvehiculosPrincipal.setForeground(new java.awt.Color(255, 255, 255));
        jBcantidadvehiculosPrincipal.setText("Cantidad de vehiculos ingresados en el día");
        jBcantidadvehiculosPrincipal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBcantidadvehiculosPrincipalActionPerformed(evt);
            }
        });

        jBbuscarplacaPrincipal.setBackground(new java.awt.Color(227, 227, 124));
        jBbuscarplacaPrincipal.setIcon(new javax.swing.ImageIcon("C:\\Users\\Usuario\\Desktop\\sd\\Parqueadero\\src\\main\\java\\GUI\\recursos\\image\\busqueda.png")); // NOI18N
        jBbuscarplacaPrincipal.setBorderPainted(false);
        jBbuscarplacaPrincipal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBbuscarplacaPrincipalActionPerformed(evt);
            }
        });

        jSbuscarporplacaPrincipal.setForeground(new java.awt.Color(0, 0, 0));

        jLbuscarporplacaPrincipal.setText("Buscar por placa");

        jSgestiondeinformacionPrincipal.setForeground(new java.awt.Color(0, 0, 0));

        jLgestiondeinformacionPrincipal.setText("Gestión de información");

        javax.swing.GroupLayout jPinformesPrincipalLayout = new javax.swing.GroupLayout(jPinformesPrincipal);
        jPinformesPrincipal.setLayout(jPinformesPrincipalLayout);
        jPinformesPrincipalLayout.setHorizontalGroup(
            jPinformesPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPinformesPrincipalLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPinformesPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jBimprimirdatosPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBcantidadvehiculosPrincipal)
                    .addGroup(jPinformesPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLgestiondeinformacionPrincipal)
                        .addComponent(jLbuscarporplacaPrincipal)
                        .addGroup(jPinformesPrincipalLayout.createSequentialGroup()
                            .addGap(8, 8, 8)
                            .addComponent(jTplacaPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(jBbuscarplacaPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jSgestiondeinformacionPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, 341, Short.MAX_VALUE)
                        .addComponent(jSbuscarporplacaPrincipal))
                    .addComponent(jBimprimirpuestosPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 120, Short.MAX_VALUE))
        );
        jPinformesPrincipalLayout.setVerticalGroup(
            jPinformesPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPinformesPrincipalLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLgestiondeinformacionPrincipal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSgestiondeinformacionPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addComponent(jBimprimirpuestosPrincipal)
                .addGap(18, 18, 18)
                .addComponent(jBcantidadvehiculosPrincipal)
                .addGap(18, 18, 18)
                .addComponent(jBimprimirdatosPrincipal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLbuscarporplacaPrincipal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSbuscarporplacaPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPinformesPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTplacaPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBbuscarplacaPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(102, 102, 102))
        );

        jTabbedPanelPrincipal.addTab("Informes", jPinformesPrincipal);

        jPoperacionesbasicasPrincipal.setBackground(new java.awt.Color(227, 227, 124));

        jBingresarvehiculoPrincipal.setBackground(new java.awt.Color(0, 0, 0));
        jBingresarvehiculoPrincipal.setForeground(new java.awt.Color(255, 255, 255));
        jBingresarvehiculoPrincipal.setText("Ingresar Vehiculo");
        jBingresarvehiculoPrincipal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBingresarvehiculoPrincipalActionPerformed(evt);
            }
        });

        jBretirarvehiculoPrincipal.setBackground(new java.awt.Color(0, 0, 0));
        jBretirarvehiculoPrincipal.setForeground(new java.awt.Color(255, 255, 255));
        jBretirarvehiculoPrincipal.setText("Retirar vehiculo");
        jBretirarvehiculoPrincipal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBretirarvehiculoPrincipalActionPerformed(evt);
            }
        });

        jBverificarespacioPrincipal.setBackground(new java.awt.Color(0, 0, 0));
        jBverificarespacioPrincipal.setForeground(new java.awt.Color(255, 255, 255));
        jBverificarespacioPrincipal.setText("Verificar Espacio");
        jBverificarespacioPrincipal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBverificarespacioPrincipalActionPerformed(evt);
            }
        });

        jLpisoPrincipal.setText("Piso");

        jLespacioPrincipal.setText("Espacio");

        jSverificaciondisponibilidadPrincipal.setForeground(new java.awt.Color(0, 0, 0));

        jLverificaciondisponibilidadPrincipal.setText("Verificación de disponibilidad");

        jSingresoyretirosvehiculosPrincipal.setForeground(new java.awt.Color(0, 0, 0));

        jLingresoyretirosvehiculosPrincipal.setText("Ingreso y retiro de Vehiculos");

        javax.swing.GroupLayout jPoperacionesbasicasPrincipalLayout = new javax.swing.GroupLayout(jPoperacionesbasicasPrincipal);
        jPoperacionesbasicasPrincipal.setLayout(jPoperacionesbasicasPrincipalLayout);
        jPoperacionesbasicasPrincipalLayout.setHorizontalGroup(
            jPoperacionesbasicasPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPoperacionesbasicasPrincipalLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPoperacionesbasicasPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPoperacionesbasicasPrincipalLayout.createSequentialGroup()
                        .addGroup(jPoperacionesbasicasPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPoperacionesbasicasPrincipalLayout.createSequentialGroup()
                                .addGroup(jPoperacionesbasicasPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTFpisoPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPoperacionesbasicasPrincipalLayout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(jLpisoPrincipal)))
                                .addGroup(jPoperacionesbasicasPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPoperacionesbasicasPrincipalLayout.createSequentialGroup()
                                        .addGap(46, 46, 46)
                                        .addComponent(jLespacioPrincipal))
                                    .addGroup(jPoperacionesbasicasPrincipalLayout.createSequentialGroup()
                                        .addGap(38, 38, 38)
                                        .addComponent(jTFespacioPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jBverificarespacioPrincipal)
                                .addGap(47, 47, 47))
                            .addComponent(jSverificaciondisponibilidadPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPoperacionesbasicasPrincipalLayout.createSequentialGroup()
                                .addGroup(jPoperacionesbasicasPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLverificaciondisponibilidadPrincipal)
                                    .addComponent(jBingresarvehiculoPrincipal))
                                .addGap(23, 23, 23)
                                .addComponent(jBretirarvehiculoPrincipal)))
                        .addContainerGap(112, Short.MAX_VALUE))
                    .addGroup(jPoperacionesbasicasPrincipalLayout.createSequentialGroup()
                        .addGroup(jPoperacionesbasicasPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSingresoyretirosvehiculosPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLingresoyretirosvehiculosPrincipal))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPoperacionesbasicasPrincipalLayout.setVerticalGroup(
            jPoperacionesbasicasPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPoperacionesbasicasPrincipalLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLingresoyretirosvehiculosPrincipal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSingresoyretirosvehiculosPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(jPoperacionesbasicasPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBingresarvehiculoPrincipal)
                    .addComponent(jBretirarvehiculoPrincipal))
                .addGap(48, 48, 48)
                .addComponent(jLverificaciondisponibilidadPrincipal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSverificaciondisponibilidadPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPoperacionesbasicasPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLpisoPrincipal, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLespacioPrincipal, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPoperacionesbasicasPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jBverificarespacioPrincipal)
                    .addGroup(jPoperacionesbasicasPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTFpisoPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTFespacioPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(106, Short.MAX_VALUE))
        );

        jTabbedPanelPrincipal.addTab("Operaciones Basicas", jPoperacionesbasicasPrincipal);

        jPterminardiaPrincipal.setBackground(new java.awt.Color(227, 227, 124));

        jBcerrarsesionPrincipal.setBackground(new java.awt.Color(227, 227, 124));
        jBcerrarsesionPrincipal.setIcon(new javax.swing.ImageIcon("C:\\Users\\Usuario\\Desktop\\sd\\Parqueadero\\src\\main\\java\\GUI\\recursos\\image\\cerrar-sesion.png")); // NOI18N
        jBcerrarsesionPrincipal.setBorderPainted(false);
        jBcerrarsesionPrincipal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBcerrarsesionPrincipalActionPerformed(evt);
            }
        });

        jSterminardiaPrincipal.setForeground(new java.awt.Color(0, 0, 0));

        jLterminardiaPrincipal.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLterminardiaPrincipal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLterminardiaPrincipal.setText("Cerrar sesión");

        javax.swing.GroupLayout jPterminardiaPrincipalLayout = new javax.swing.GroupLayout(jPterminardiaPrincipal);
        jPterminardiaPrincipal.setLayout(jPterminardiaPrincipalLayout);
        jPterminardiaPrincipalLayout.setHorizontalGroup(
            jPterminardiaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPterminardiaPrincipalLayout.createSequentialGroup()
                .addGap(0, 53, Short.MAX_VALUE)
                .addComponent(jSterminardiaPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 387, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41))
            .addGroup(jPterminardiaPrincipalLayout.createSequentialGroup()
                .addGroup(jPterminardiaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPterminardiaPrincipalLayout.createSequentialGroup()
                        .addGap(153, 153, 153)
                        .addComponent(jLterminardiaPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPterminardiaPrincipalLayout.createSequentialGroup()
                        .addGap(205, 205, 205)
                        .addComponent(jBcerrarsesionPrincipal)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPterminardiaPrincipalLayout.setVerticalGroup(
            jPterminardiaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPterminardiaPrincipalLayout.createSequentialGroup()
                .addContainerGap(85, Short.MAX_VALUE)
                .addComponent(jLterminardiaPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jSterminardiaPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(jBcerrarsesionPrincipal)
                .addGap(118, 118, 118))
        );

        jTabbedPanelPrincipal.addTab("Terminar Dia", jPterminardiaPrincipal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPanelPrincipal)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPanelPrincipal)
        );

        setSize(new java.awt.Dimension(502, 412));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jBfijarPrincipalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBfijarPrincipalActionPerformed
        
        
        pisos = Integer.parseInt(jTFpisosPrincipal.getText());
        espacio = Integer.parseInt(jTFespaciosPrincipal.getText());
        precioCarro = Integer.parseInt(jTFvalorcarroPrincipal.getText());
        precioMoto = Integer.parseInt(jTFvalormotoPrincipal.getText());

     
        Vehiculo.vehiculos = new Vehiculo[pisos][espacio];
        Sensor.sensores = new Sensor[pisos][espacio];

        jTFpisosPrincipal.setText("");
        jTFespaciosPrincipal.setText("");
        jTFvalorcarroPrincipal.setText("");
        jTFvalormotoPrincipal.setText("");

        jTFpisosPrincipal.setBackground(Color.GRAY);
        jTFespaciosPrincipal.setBackground(Color.GRAY);
        jTFvalorcarroPrincipal.setBackground(Color.GRAY);
        jTFvalormotoPrincipal.setBackground(Color.GRAY);

        jTFpisosPrincipal.setEnabled(false);
        jTFespaciosPrincipal.setEnabled(false);
        jTFvalorcarroPrincipal.setEnabled(false);
        jTFvalormotoPrincipal.setEnabled(false);

        JOptionPane.showMessageDialog(new JFrame(), "Se ha fijado correctamente la configuración");
             
        


    }//GEN-LAST:event_jBfijarPrincipalActionPerformed

    private void jBsalirPrincipalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBsalirPrincipalActionPerformed
        this.dispose();
    }//GEN-LAST:event_jBsalirPrincipalActionPerformed

    private void jBingresarvehiculoPrincipalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBingresarvehiculoPrincipalActionPerformed

        GUIIngresoVehiculo ventanaIngresoVehiculo = new GUIIngresoVehiculo();
        ventanaIngresoVehiculo.setVisible(true);

    }//GEN-LAST:event_jBingresarvehiculoPrincipalActionPerformed

    private void jBimprimirdatosPrincipalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBimprimirdatosPrincipalActionPerformed

        try {
            FileWriter informe = new FileWriter("C:\\Users\\Usuario\\Desktop\\informe.csv");

            informe.write(Vehiculo.toStringVehiculos());
   
            informe.close();
        } catch (IOException e) {
            System.out.println("An error occurred.");

        }

        System.out.println(Vehiculo.toStringVehiculos());

    }//GEN-LAST:event_jBimprimirdatosPrincipalActionPerformed

    private void jBcantidadvehiculosPrincipalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBcantidadvehiculosPrincipalActionPerformed

        int cantidad_vehiculos = Vehiculo.cantidadVehiculos();
        JOptionPane.showMessageDialog(this, "Se ha ingresado un total de " + cantidad_vehiculos + " Vehículos en el día", "Información", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jBcantidadvehiculosPrincipalActionPerformed

    private void jBbuscarplacaPrincipalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBbuscarplacaPrincipalActionPerformed

        String mensaje = Vehiculo.Placa(jTplacaPrincipal.getText());
        JOptionPane.showMessageDialog(this, mensaje, "Información", JOptionPane.INFORMATION_MESSAGE);

        jTplacaPrincipal.setText("");

    }//GEN-LAST:event_jBbuscarplacaPrincipalActionPerformed

    private void jBimprimirpuestosPrincipalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBimprimirpuestosPrincipalActionPerformed

        GUIEstadoPuestos VentanaEstadoPuestos = new GUIEstadoPuestos();
        VentanaEstadoPuestos.setVisible(true);

        DefaultTableModel tabla_info = new DefaultTableModel();

        tabla_info.addColumn("Piso");
        tabla_info.addColumn("Espacio");
        tabla_info.addColumn("Estado");
        VentanaEstadoPuestos.jTEstadoPuestos.setModel(tabla_info);

        String[] datos = new String[3];

        for (int i = 0; i < Sensor.sensores.length; i++) {
            for (int j = 0; j < Sensor.sensores[0].length; j++) {
                if (Sensor.sensores[i][j] == null) {

                    datos[0] = Integer.toString(i);
                    datos[1] = Integer.toString(j);
                    datos[2] = "Libre";
                    tabla_info.addRow(datos);

                } else {

                    datos[0] = Integer.toString(i);
                    datos[1] = Integer.toString(j);
                    datos[2] = "Ocupado";
                    tabla_info.addRow(datos);
                }

            }
        }

        //datos.addRow(sensor_dia);
        // System.out.println(Sensor.sensoresEstado());

    }//GEN-LAST:event_jBimprimirpuestosPrincipalActionPerformed

    private void jBreiniciarPrincipalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBreiniciarPrincipalActionPerformed

        jTFpisosPrincipal.setText("");
        jTFespaciosPrincipal.setText("");
        jTFvalorcarroPrincipal.setText("");
        jTFvalormotoPrincipal.setText("");
        
        jTFpisosPrincipal.setBackground(Color.WHITE);
        jTFespaciosPrincipal.setBackground(Color.WHITE);
        jTFvalorcarroPrincipal.setBackground(Color.WHITE);
        jTFvalormotoPrincipal.setBackground(Color.WHITE);
        
        jTFpisosPrincipal.setEnabled(true);
        jTFespaciosPrincipal.setEnabled(true);
        jTFvalorcarroPrincipal.setEnabled(true);
        jTFvalormotoPrincipal.setEnabled(true);
        
       
       
    }//GEN-LAST:event_jBreiniciarPrincipalActionPerformed

    private void jBverificarespacioPrincipalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBverificarespacioPrincipalActionPerformed

        if (Sensor.sensores[Integer.parseInt(jTFpisoPrincipal.getText())][Integer.parseInt(jTFespacioPrincipal.getText())] == null) {
            JOptionPane.showMessageDialog(this, "Espacio Libre", "Información", JOptionPane.INFORMATION_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(this, "Espacio LLeno", "Información", JOptionPane.INFORMATION_MESSAGE);
        }
        jTFpisoPrincipal.setText("");
        jTFespacioPrincipal.setText("");
    }//GEN-LAST:event_jBverificarespacioPrincipalActionPerformed

    private void jBfijarPrincipalMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBfijarPrincipalMouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_jBfijarPrincipalMouseMoved

    private void jBcerrarsesionPrincipalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBcerrarsesionPrincipalActionPerformed
        
        GUILogin VentanaLogin = new GUILogin();
        VentanaLogin.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jBcerrarsesionPrincipalActionPerformed

    private void jBretirarvehiculoPrincipalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBretirarvehiculoPrincipalActionPerformed
        GUIRetirarVehiculo  GUIRetirarVehiculo = new  GUIRetirarVehiculo();
         GUIRetirarVehiculo.setVisible(true);
    }//GEN-LAST:event_jBretirarvehiculoPrincipalActionPerformed

    private void jTFvalorcarroPrincipalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFvalorcarroPrincipalActionPerformed
         
        precioCarro = Integer.parseInt(jTFvalorcarroPrincipal.getText());
        
    }//GEN-LAST:event_jTFvalorcarroPrincipalActionPerformed

    private void jTFespaciosPrincipalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFespaciosPrincipalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFespaciosPrincipalActionPerformed

    private void jTFvalormotoPrincipalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFvalormotoPrincipalActionPerformed
        
        precioMoto = Integer.parseInt(jTFvalormotoPrincipal.getText());
    }//GEN-LAST:event_jTFvalormotoPrincipalActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        GUIRetirarVehiculo  GUIRetirarVehiculo = new  GUIRetirarVehiculo();
         GUIRetirarVehiculo.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUIPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUIPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUIPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUIPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUIPrincipal().setVisible(true);
            }
        });

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBbuscarplacaPrincipal;
    private javax.swing.JButton jBcantidadvehiculosPrincipal;
    private javax.swing.JButton jBcerrarsesionPrincipal;
    private javax.swing.JButton jBfijarPrincipal;
    private javax.swing.JButton jBimprimirdatosPrincipal;
    private javax.swing.JButton jBimprimirpuestosPrincipal;
    private javax.swing.JButton jBingresarvehiculoPrincipal;
    private javax.swing.JButton jBreiniciarPrincipal;
    private javax.swing.JButton jBretirarvehiculoPrincipal;
    private javax.swing.JButton jBsalirPrincipal;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jBverificarespacioPrincipal;
    private javax.swing.JLabel jLbuscarporplacaPrincipal;
    private javax.swing.JLabel jLespacioPrincipal;
    private javax.swing.JLabel jLespaciosPrincipal;
    private javax.swing.JLabel jLgestiondeinformacionPrincipal;
    private javax.swing.JLabel jLingresoyretirosvehiculosPrincipal;
    private javax.swing.JLabel jLpisoPrincipal;
    private javax.swing.JLabel jLpisosPrincipal;
    private javax.swing.JLabel jLpropiedadesPrincipal;
    private javax.swing.JLabel jLterminardiaPrincipal;
    private javax.swing.JLabel jLvalorcarroPrincipal;
    private javax.swing.JLabel jLvaloresmonetariosPrincipal;
    private javax.swing.JLabel jLvalormotoPrincipal;
    private javax.swing.JLabel jLverificaciondisponibilidadPrincipal;
    private javax.swing.JPanel jPconfiguracioninicialPrincipal;
    private javax.swing.JPanel jPinformesPrincipal;
    private javax.swing.JPanel jPoperacionesbasicasPrincipal;
    private javax.swing.JPanel jPterminardiaPrincipal;
    private javax.swing.JSeparator jSbuscarporplacaPrincipal;
    private javax.swing.JSeparator jSgestiondeinformacionPrincipal;
    private javax.swing.JSeparator jSingresoyretirosvehiculosPrincipal;
    private javax.swing.JSeparator jSpropiedadesPrincipal;
    private javax.swing.JSeparator jSterminardiaPrincipal;
    private javax.swing.JSeparator jSvaloresmonetariosPrincipal;
    private javax.swing.JSeparator jSverificaciondisponibilidadPrincipal;
    private javax.swing.JTextField jTFespacioPrincipal;
    private javax.swing.JTextField jTFespaciosPrincipal;
    private javax.swing.JTextField jTFpisoPrincipal;
    private javax.swing.JTextField jTFpisosPrincipal;
    public static javax.swing.JTextField jTFvalorcarroPrincipal;
    public static javax.swing.JTextField jTFvalormotoPrincipal;
    private javax.swing.JTabbedPane jTabbedPanelPrincipal;
    private javax.swing.JTextField jTplacaPrincipal;
    // End of variables declaration//GEN-END:variables
}
